In [68]:
import pandas as pd
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [69]:
netflix = pd.read_csv('netflix.csv')

In [70]:
# netflix['index'] = netflix['index'].astype(int)

In [71]:
netflix.head()

index show_id     type                  title         director   
0      0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson  \
1      1      s2  TV Show          Blood & Water              NaN   
2      2      s3  TV Show              Ganglands  Julien Leclercq   
3      3      s4  TV Show  Jailbirds New Orleans              NaN   
4      4      s5  TV Show           Kota Factory              NaN   

                                                cast   
0                                                NaN  \
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...   
3                                                NaN   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...   

                                           listed_in   
0                                      Documentaries  \
1    International TV Shows, TV Dramas, TV Mysteries   
2  Crime TV Shows, International TV Shows, TV Act...   
3                             Docuseries, Reality TV   
4  International TV Shows, Romantic TV Shows, TV ...   

                                         description  
0  As her father nears the end of his life, filmm...  
1  After crossing paths at a party, a Cape Town t...  
2  To protect his family from a powerful drug lor...  
3  Feuds, flirtations and toilet talk go down amo...  
4  In a city of coaching centers known to train I...

In [72]:
for columns in netflix:
    netflix[columns] = netflix[columns].fillna('')

In [73]:
netflix.head()

index show_id     type                  title         director   
0      0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson  \
1      1      s2  TV Show          Blood & Water                    
2      2      s3  TV Show              Ganglands  Julien Leclercq   
3      3      s4  TV Show  Jailbirds New Orleans                    
4      4      s5  TV Show           Kota Factory                    

                                                cast   
0                                                     \
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...   
3                                                      
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...   

                                           listed_in   
0                                      Documentaries  \
1    International TV Shows, TV Dramas, TV Mysteries   
2  Crime TV Shows, International TV Shows, TV Act...   
3                             Docuseries, Reality TV   
4  International TV Shows, Romantic TV Shows, TV ...   

                                         description  
0  As her father nears the end of his life, filmm...  
1  After crossing paths at a party, a Cape Town t...  
2  To protect his family from a powerful drug lor...  
3  Feuds, flirtations and toilet talk go down amo...  
4  In a city of coaching centers known to train I...

In [74]:
combine_columns = netflix['director'] + ' ' + netflix['cast'] + ' ' + netflix['listed_in'] + ' ' +netflix['description']

In [75]:
print(combine_columns)

0       Kirsten Johnson  Documentaries As her father n...
1        Ama Qamata, Khosi Ngema, Gail Mabalane, Thaba...
2       Julien Leclercq Sami Bouajila, Tracy Gotoas, S...
3         Docuseries, Reality TV Feuds, flirtations an...
4        Mayur More, Jitendra Kumar, Ranjan Raj, Alam ...
                              ...                        
8802    David Fincher Mark Ruffalo, Jake Gyllenhaal, R...
8803      Kids' TV, Korean TV Shows, TV Comedies While...
8804    Ruben Fleischer Jesse Eisenberg, Woody Harrels...
8805    Peter Hewitt Tim Allen, Courteney Cox, Chevy C...
8806    Mozez Singh Vicky Kaushal, Sarah-Jane Dias, Ra...
Length: 8807, dtype: object


In [76]:
vectorizer = TfidfVectorizer()
feature_vector = vectorizer.fit_transform(combine_columns)
print(feature_vector)

  (0, 20809)	0.2841863252556119
  (0, 14626)	0.16913069201666656
  (0, 6159)	0.17557045885474756
  (0, 44693)	0.1374892018558456
  (0, 19174)	0.13884422174215158
  (0, 45125)	0.05002355549365097
  (0, 48040)	0.19161453714007637
  (0, 9335)	0.26226231183427406
  (0, 2136)	0.04940022801902621
  (0, 21126)	0.26226231183427406
  (0, 20682)	0.05858781394964171
  (0, 10953)	0.15314035998970643
  (0, 42314)	0.2354625639827521
  (0, 15309)	0.19335605947154055
  (0, 25729)	0.10618655221017058
  (0, 19595)	0.14274933476478932
  (0, 32018)	0.05521237759144405
  (0, 13774)	0.1889094994065815
  (0, 44666)	0.09416284115083559
  (0, 30896)	0.25738657740408993
  (0, 14931)	0.13708368777013225
  (0, 19270)	0.08724305356022215
  (0, 3047)	0.09580518184827762
  (0, 12263)	0.10477726015522837
  (0, 22237)	0.3360798116105061
  :	:
  (8806, 39492)	0.17676655052945897
  (8806, 14640)	0.15623924826255076
  (8806, 27082)	0.1465409141050715
  (8806, 23185)	0.15057178968323714
  (8806, 450)	0.0981661991489945
  

In [77]:
similarity = cosine_similarity(feature_vector)
print(similarity)

[[1.         0.0051327  0.0203364  ... 0.0092648  0.01422661 0.02977867]
 [0.0051327  1.         0.02107557 ... 0.00102995 0.         0.00267091]
 [0.0203364  0.02107557 1.         ... 0.00558439 0.01034976 0.03055661]
 ...
 [0.0092648  0.00102995 0.00558439 ... 1.         0.05574805 0.00493706]
 [0.01422661 0.         0.01034976 ... 0.05574805 1.         0.0094404 ]
 [0.02977867 0.00267091 0.03055661 ... 0.00493706 0.0094404  1.        ]]


In [78]:
movie_name = input("Enter the movie name \n")

Enter the movie name 
manga


In [79]:
title_list = netflix['title'].tolist()
print(title_list)

['Dick Johnson Is Dead', 'Blood & Water', 'Ganglands', 'Jailbirds New Orleans', 'Kota Factory', 'Midnight Mass', 'My Little Pony: A New Generation', 'Sankofa', 'The Great British Baking Show', 'The Starling', 'Vendetta: Truth, Lies and The Mafia', 'Bangkok Breaking', 'Je Suis Karl', 'Confessions of an Invisible Girl', 'Crime Stories: India Detectives', 'Dear White People', "Europe's Most Dangerous Man: Otto Skorzeny in Spain", 'Falsa identidad', 'Intrusion', 'Jaguar', 'Monsters Inside: The 24 Faces of Billy Milligan', 'Resurrection: Ertugrul', 'Avvai Shanmughi', 'Go! Go! Cory Carson: Chrissy Takes the Wheel', 'Jeans', 'Love on the Spectrum', 'Minsara Kanavu', 'Grown Ups', 'Dark Skies', 'Paranoia', 'Ankahi Kahaniya', 'Chicago Party Aunt', 'Sex Education', 'Squid Game', 'Tayo and Little Wizards', 'The Father Who Moves Mountains', 'The Stronghold', 'Angry Birds', 'Birth of the Dragon', 'Chhota Bheem', 'He-Man and the Masters of the Universe', 'Jaws', 'Jaws 2', 'Jaws 3', 'Jaws: The Revenge

In [80]:
find_match = difflib.get_close_matches(movie_name, title_list)
print(find_match)

['Sangam', 'Dangal', 'Hangman']


In [81]:
close_match = find_match[0]

In [82]:
# movie_index = netflix[netflix.title == close_match]['index'].values[0]
# print(movie_index)
movie_index = netflix[netflix['title'] == close_match]['index'].values
if len(movie_index) > 0:
    movie_index = movie_index[0]
else:
    print("Movie not found,")
    exit()

In [83]:
similarity_score = list(enumerate(similarity[movie_index]))

In [84]:
sort_movie = sorted(similarity_score, key=lambda x:x[1], reverse=True)
print(sort_movie)

[(7932, 1.0), (7133, 0.22854138428951698), (6350, 0.18010649118571992), (7827, 0.1646372224030843), (6289, 0.16141546209765392), (5080, 0.15309242249658397), (5587, 0.1387852068723529), (2286, 0.12561366432212884), (3950, 0.12555047379518797), (6107, 0.1253234960848158), (2723, 0.12282899175374835), (7557, 0.12095662728983209), (199, 0.12065060104383862), (203, 0.11943474315157375), (8098, 0.11709947357476298), (2721, 0.11633796351746861), (8023, 0.1155903019549207), (7994, 0.11421641777256003), (2738, 0.11258640450129612), (1974, 0.11025779766272421), (4792, 0.10853246082417717), (201, 0.10814118044605577), (3975, 0.10748165301670792), (4563, 0.10664579644440979), (2830, 0.1063750958214035), (7913, 0.10587278817222574), (5461, 0.10584988017307279), (1858, 0.10544419091155348), (5303, 0.10523228058884748), (6960, 0.10344261715463952), (5515, 0.1020402854105402), (2733, 0.10128689055467285), (2629, 0.10083014137279724), (1940, 0.10082091980516651), (4610, 0.10026113664757598), (3299, 0.

In [87]:
i=1
for movies in sort_movie:
    index = movies[0]
    title_from_index = netflix[netflix.index==index]['title'].values[0]
    
    if(i<=20):
        print(i, title_from_index)
    i+=1

1 Sangam
2 Jis Desh Men Ganga Behti Hai
3 Bobby
4 Ram Teri Ganga Maili
5 Bewafaa
6 Pyar Ke Do Pal
7 Force 2
8 Pyaar Ka Punchnama 2
9 Ek Ladki Ko Dekha Toh Aisa Laga
10 Aitraaz
11 Friendship
12 Namak Halaal
13 Koi Aap Sa
14 Kyaa Kool Hain Hum 3
15 Story of an Egg
16 Duniya
17 Singh Saab the Great
18 Shakti: The Power
19 Muqaddar ka Faisla
20 Saheb Biwi Aur Gangster Returns
